#! /usr/bin/env python3
# De-duplicates and filters raw data. 
# Only selects servers where English is an official language

import json, os, pathlib
from .... import CONFIG, Config

servers = {}
DATA_REPO = pathlib.Path(CONFIG[Config._mastodon][Config._datarepo])

# TODO: this should be in the project-configs, autogenerated at instance fetch time
root = DATA_REPO.joinpath('data', *__package__.replace('clean', 'fetch').split('.'))

for folder in root.iterdir():
    for filename in folder.iterdir():
        with open(filename, 'r') as f:
            for line in f:
                data = json.loads(line)
                if 'domain' in data:
                    domain = data['domain']
                    if domain not in servers:
                        servers[domain] = data

parent_dir = DATA_REPO.joinpath('data', *__package__.split('.'))
parent_dir.mkdir(parents=True, exist_ok=True)

with open(parent_dir.joinpath('serverlist.jsons'), 'w') as f:
    for instance in servers.values():
        json.dump(instance, f)
        f.write('\n')

print(len(servers), 'unique servers')